# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5c74e6ae73e400825361721cd13427dfc956ad9d418a894dd9c0b61ad3bf142fcf40242bd2f8e48ad4bc143779db430c596f35eddb6d090f3d0caab115c3de7

test:
  secret_key_base: d2ade31163309fa4b189bb0a914a8079491717df675159261505646a8d2bfb1ee2e098a9986f9222003093df8a5c5c5fa46360dda4a35bed6845ff7a5c57338a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
